### ISSUE TITLE
Discovery of changes for referenced resources

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#12]
In order to build a robust search engine, it is necessary to know that referenced metadata resources, via `seeAlso`, have changed even if the Manifest has not changed itself.  Equally, if a search engine can process images, it would need to know about changes to those images (or any other content!)

The current scope of the work is for IIIF resources (charter section 1a), rather than all referenced resources.  While this is important, it's not within our remit right now. 

The agreement on discovery call (2018-02-07) was to clarify the scope of the work to be only Manifests and Collections, and defer referenced until we have things better nailed down.

**Comment by aisaac** [comment]
NB: #41 provides another use case for non-IIIF resources.
