### ISSUE TITLE
Improving introduction for Level 0

### ISSUE THREAD

**Issue by aisaac** [IIIF/discovery#13]
This issue addressed the action in call of 2018-02-07: Rob (or Antoine) will improve the introduction to level 0.

I'm hereby suggesting a small re-write of this introduction:
- removing a '"just" which I felt minimized a bit much the effort asked for the people only interested in a basic crawling.
- re-ordered the last paragraph to mention the other items in the charter, so as to bring more motivation for the extra complexity.

Here it is:

> The basic information required, in order to provide a minimally effective set of links to Manifests to harvest is just the URIs of the Manifests. However, with the addition of a little boilerplate in the JSON, we can be on the path towards a robust set of metadata that allows clients to optimize their harvesting. 
>
> Starting with the Manifest links, we add an "Update" activity wrapper around the URIs. The order of the Manifests in the pages is unimportant, but each should only appear once. 
> 
> In terms of optimization, Level 0 provides no additional benefit over any other simpler list format, but is compatible with a system where optimization is possible, such as the following levels, which bring significant improvements in terms of efficiency. This is also the minimum level for interoperability on the way to realizing a complete and homogeneous framework that addresses more items from the IIIF Discovery Technical Specification Group Charter [http://iiif.io/community/groups/discovery/charter/#introduction].

**Comment by aisaac** [comment]
@azaroth42 is it ok for you?

**Comment by azaroth42** [comment]
Yup.  Made a few minor tweaks to avoid talking about the charter in an API doc.
