### ISSUE TITLE
Link in readme.md to doesn't go anywhere

### ISSUE THREAD

**Issue by glenrobson** [IIIF/discovery#15]
The link in the readme for 'Working Draft of an Import specification' links to:

https://github.com/IIIF/iiif.io/discovery/blob/master/source/api/image/0.1/index.md

Which doesn't exist. Where should it link to?

**Comment by zimeon** [comment]
https://github.com/IIIF/discovery/blob/master/source/api/import/0.1/index.md

**Comment by aisaac** [comment]
Fixed by https://github.com/IIIF/discovery/commit/f66dcd0d5a8f9c4c0e275395fdc60d5980d53a47
