### ISSUE TITLE
Import to Viewers

### ISSUE THREAD

**Issue by glenrobson** [IIIF/discovery#18]
This is a ticket to gather together the discussions in Toronto. Related reading:

 * Notes from the Discovery session in Toronto: https://docs.google.com/document/d/1PVYzT1jRTE2jtwzOwyhOcg6Rf8CCdrJ-kP6sYOpV_j0/edit - Heading 'IIIF Import to viewers'
 * Related discussion on software dev channel: https://iiif.slackarchive.io/softwaredevs/page-10/ts-1508144299000347
 * Related discussion on discovery channel: https://iiif.slackarchive.io/discovery/page-9/ts-1507910636000184
 * Related UV issue: https://github.com/UniversalViewer/universalviewer/issues/562

It looks like the discussion in Toronto ended with:

"Work out good cut and paste pattern, generalise to drag and drop"

Tom came up with the following annotation that could encode the state of a viewer in an annotation:

```
{
  "type": "Annotation",
  "motivation": "highlighting",
  "target": {
   {
	  "start": {
	    "type": "SpecificResource",
	    "source": {
	      "id": "https://example.org/iiif/id1/canvas1",
	      "type": "Canvas",
	      "within": {
		"id": "https://example.org/iiif/id1/manifest",
		"type": "Manifest"
	     }
	    },
	    "selector": {
	      "type": "PointSelector",
	      "x": 10,
	      "y": 10,
	      "t": 14.5
	  }
   },
   "generator": { 
        // UV state encoded here? 
    }
}
```

So questions I have is how do we transmit the above data from a page to a viewer? How do we support:
 * Copy and paste
 * Drag and drop
 * Other interactions?

**Comment by azaroth42** [comment]
@mejackreed ^^^

**Comment by mejackreed** [comment]
What do you think about this type of pattern @2SC1815J ?

**Comment by 2SC1815J** [comment]
I think it is a nice proposal, for ignorable information is capsuled in `generator`.

If this pattern will not be used in static HTML pages, a IIIF viewer which generates the above data might be able to apply the DataTransfer.setData() of the HTML 5 Drag and Drop API to a [IIIF drag and drop link icon](http://zimeon.github.io/iiif-dragndrop/). 
In this case, even if the drop target is an old IIIF viewer, the link target will open correctly.
(However, it may not be a good choice to specify such an implementation detail.)

If you want to transmit the above data from a page to a viewer while the target viewer is not open, how can it be done? (URI Scheme? Browser extension?)

**Comment by tomcrane** [comment]
Propose close as this has been superseded by the evolving spec.

The note about `generator` is valid, but would that be spec? It's for individual apps to encode extra non-content stuff, which is up to them.

**Comment by aisaac** [comment]
Closed in call 14 May 2020
