### ISSUE TITLE
Document the cut/paste JSON structure

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#19]
Based on #18.

**Comment by tomcrane** [comment]
First attempt at this:

https://docs.google.com/document/d/1LKhEWWuYF-8KLkKcW_u2GlvX0epohwc7OYOVjICie5M/edit#

**Comment by glenrobson** [comment]
Just playing around trying to implement this with copy and paste. Should the JSON data that is copied be copied as a Javascript Objects or as a string? Is this a spec or implementation question? 

String would allow copying between browser and desktop application...

**Comment by tomcrane** [comment]
This doc has been superseded by the spec, propose close

**Comment by aisaac** [comment]
Closed as per call 13 May 2020
