### ISSUE TITLE
Wording on collection/pages organization

### ISSUE THREAD

**Issue by aisaac** [IIIF/discovery#25]
_Warning: this is a comment that's maybe better to address for future versions of the spec, post Washington, not now!_

Section 3.1 reads “The top-most resource for managing the lists of Activities is an Ordered Collection, broken up into Ordered Collection Pages. This is the same pattern that the Web Annotation model uses for Annotation Collections and Annotation Pages. The Collection does not directly contain any of the Activities, instead it refers to the first and last pages of the list.”
Sections 2.4 and 2.5 also prescribe the way activities should be gathered in pages and ordered collections. 

Should we make stronger the wording of all this? It is rather clear for me, but one could say it remains implicit. It could be questions, whether this organization is mandatory, especially in corner cases where a collection of resources/activities would be small.

**Comment by azaroth42** [comment]
:+1:  The wording is currently still very descriptive, rather than normative.  There's no "Publishers MUST ..." anywhere. Will work on it, maybe for after Washington if it needs huge changes.

**Comment by azaroth42** [comment]
Done in the intro blocks for section 3.

**Comment by aisaac** [comment]
It's fine for me!
