### ISSUE TITLE
Various editorial issues and suggestions for current Discovery draft

### ISSUE THREAD

**Issue by aisaac** [IIIF/discovery#26]
On http://preview.iiif.io/api/discovery/api/discovery/0.1/, April 23 2018

Sec 2.2: the first parts of the list, once finished, can become static resources.
-> I feel this will mostly happen for the the case when there are no deleted resources, of if deleted resources are indicated as per level 2 (i.e. creation of new deletion activity for the resources, which will allow not to update the earlier ‘update’ activity for these). For level 1 and level 0 it is likely that the pages won’t be static if there are deletions. As the sentence is in the section for level 1, maybe this is worth flagging?

Sec 3: “The W3C Activity Streams specification defines a “model for representing potential and completed activities”, and is compatible with the design patterns established for IIIF APIs. It is defined in terms of JSON-LD, and can be seamlessly integrated with the existing IIIF APIs.” I feel this could be put earlier in the spec - AS has been used already quite a lot before. Maybe in the intro for section 2.

Sec 3: “Properties that the consuming application does not understand MUST be ignored.”
I’m really not sure what an implementer could do with this. Does it mean that we say stuff in the spec, but implementers (of publication systems) should adapt their work to what any consuming system may ingest or not?
This seems quite dangerous even, as a lot of the properties in section 3 are necessary for the organization of collections and pages, which seem to be mandatory (see #25)

Section 3.1 (but it also concerns 3.4 and other places about the ordering of activities):
“This might seem odd to implementers, without the context of the processing patterns expected.”
Should we add a note asking specific feedback on this, if it’s possible to be a controversial point in the spec? If we get no objection or if we successfully address the one we get, then we could highlight this in the next version, instead of having this mildly apologetic sentence in.

Section 3.3: typo “should be one of Create, Update, or Delete. z”

**Comment by azaroth42** [comment]
2.2 -- This is only true at level 1, as the set of URIs at level 0 is effectively unordered. Which doesn't mean they can't be static resources, but the incremental creation is probably not how they're built.  I've dropped the levels into a new block, and put this explanation as the intro to that block. 

Deletion is a bigger issue. At level 0-1, you can't signal that a resource was deleted, so you would need to either ignore them (the client will just get a 404) or republish your list (thereby removing them). Oddly, at level 0 you probably regenerate the entire list, and at level 1 you let the client run into the deleted resource.  Added text to that effect.

3 -- I wanted to keep section 2 reasonably informative. Hence the reference in the first paragraph of 2, but then only by example.  Section 3 is then the normative definition for requirements.

3 -- It's missing a "beyond those described in this specification" ... e.g. if you see some extension, that's fine, don't raise an error.  Fixed.

3.1 (etc) -- Agree about the mildly apologetic tone. Took out that sentence and tweaked other occurrences. 
 
3.3. -- Fixed

**Comment by aisaac** [comment]
Comments on the changes...

2.2 (now 2.1) I like the new wrapping, and the re-wording around the 'static' issue. I'm less convinced by the title. "changes" is ok for us, but too generic to give a new reader good clues about what will be found - especially if the reader is only interested in publishing list of resources. How about something like "Listing resources and their changes"?

3. (reference to AS) I can live with it.

3. (properties not in the spec) much clearer now!

3.1 I would have prefered to have an explicit call for feedback, but in any case I can live with the current wording.

3.3 thx!

**Comment by azaroth42** [comment]
Fixed title.  

Lets see what the reactions are to the text from others, on the last to first processing. If there's confusion, we can add something back in.
