### ISSUE TITLE
Discuss @context in Change Discovery API docs

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#28]
There's no mention of `@context` in the API documentation.  This is due, in part, to the realization of the complexity of context management across multiple specifications that are linked, but should not be tied together: https://github.com/IIIF/api/issues/1571

Given the ActivityStreams focus, the only entries a context needs beyond the default AS context, is the IIIF classes for the objects.  However, we need to decide (per #12 etc.) what the scope of those classes is.

The documentation is, however, incomplete without some sort of decision on this.

**Comment by aisaac** [comment]
I think I would be fine at this stage to put an editor's note pointing to here, acknowledging that we are aware of the issue and will work on it once the spec is more mature, re. the full list of elements that we want to include. This would save some effort that would have to be re-done afterwards, partly.
Would it be ok on your side?

**Comment by azaroth42** [comment]
Editorial action: Document the use of `@context` per other APIs, and refer to extension registry for additional contexts to use for non IIIF types.

**Comment by azaroth42** [comment]
@azaroth42 to do this for March 6 call.

**Comment by azaroth42** [comment]
On call of 2019-03-20: Fixed in 0.3, close.
