### ISSUE TITLE
Flowchart for algorithm

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#29]
Before merging

**Comment by zimeon** [comment]
:+1: Anything to get rid of the awful bullet and number in parens. I tried and could not coerce sensible two level numbered/lettered bullets

**Comment by azaroth42** [comment]
Yes, I tried several times as well, but couldn't get kramdown to do the right thing :(

**Comment by azaroth42** [comment]
Tried to build the workflow diagram and it got more complicated than the textually described algorithms.

**Comment by azaroth42** [comment]
Propose close won't fix unless someone has a good idea about how to do this with the current algorithm.

**Comment by aisaac** [comment]
Yes and it's not easier with the latest updates!
I'm a bit lukewarm about killing it right now, however. Maybe we could do this just before 1.0? Who knows, maybe some one could come with a suggestion between now and then.

**Comment by azaroth42** [comment]
Propose close wontfix. The algorithm flowchart got harder and harder -- the textual pseudo-code is much easier to understand.

**Comment by tomcrane** [comment]
:+1:
