### ISSUE TITLE
Which Activity Types do we care about?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#3]
In the current discussion document for crawling we list the following core types:

* Update -- the most important!
* Create -- to distinguish the initial update from subsequent
* Delete -- to allow removing already crawled resources from a discovery system

And the following additional publisher activities:

* Add -- The (e.g.) Manifest was added to a Collection
* Remove -- Opposite of Add
* Copy -- The Manifest was duplicated from an existing one
* Move -- The Manifest was moved/renamed from a previous URI
* Merge -- Two or more Manifests that were separate were merged to form a new Manifest
* Split -- A Manifest was split into two or more new Manifests

And third party activities:

* Reference -- A link was created to the Manifest by the party
* Use -- The Manifest was used by the party in some way
* Replace -- The party replaced the manifest with another one (and would like the publisher to incorporate those changes)

Which of the non-core activity types do we care about, if any?

**Comment by zimeon** [comment]
I think Merge and Split are a real stretch -- I think we should weigh carefully whether the simplify or confuse

**Comment by azaroth42** [comment]
For the mean time, only the three core properties are in the document.  If experimentation reveals a use for further types, we can add them.
