### ISSUE TITLE
CODH Activity stream

### ISSUE THREAD

**Issue by IllDepence** [IIIF/discovery#32]
In a similar fashion to #22, maybe another candidate for the list of "Ongoing Experimental Implementations".

Endpoint: https://mp.ex.nii.ac.jp/api/face/curation/as/collection.json
Implementation: https://github.com/IllDepence/JSONkeeper#activity-stream

*Caveat*: all the Create activities in the AS are for [cr:Curation](http://codh.rois.ac.jp/iiif/curation/index.html.en) documents. Reference activities however have sc:Canvas as their object. Furthermore there are Offer activities that involve sc:Range (object) and sc:Manifest (target).

**Comment by azaroth42** [comment]
Could you generate a stream for Manifests instead please?  I think it would be confusing to potential adopters at this stage to be confronted with non-IIIF resources.

**Comment by IllDepence** [comment]
The project this AS is generated for unfortunately only involves cr:Curations on the CODH's end (the Curations point at Manifests hosted by several institutions but it wouldn't make sense to generate `Create` Activities for those).

We will look into offering an AS for Manifests outside the scope of the project linked above.

**Comment by azaroth42** [comment]
Great. Propose to close this issue, and recreate when there's an AS stream for Manifests.

**Comment by IllDepence** [comment]
Agreed.
