### ISSUE TITLE
AS publishing granularity level

### ISSUE THREAD

**Issue by mixterj** [IIIF/discovery#34]
In harvesting AS data it has become apparent the knowing the level of granularity for the AS is very important but also very difficult to determine unless you are familiar with the data. We have seen instances where: 

1. AS are created at the Organization level (with multiple collections encompassed in the stream)

2 AS streams created at the Collection level (where the Organization is implied based on knowing the data well). 

This make it very difficult for an harvester/indexer to create a coherent shape for the data. One approach would be to assume Organization level AS and rely on a partOf relationship from the Manifest to the Collection descriptions but this is not specified in any of the IIIF API docs and we have not seen any such clues/references in any of the data we have harvested. Also in addition to a partOf link this approach would also require the creation and maintenance of Collection level descriptions so the harvester can generate a meaningful description (at least a label).

**Comment by aisaac** [comment]
This is a great issue to discuss, @mixterj thanks for raising it.
Is your last sentence suggesting that we may have to add some metadata about the context of the stream? This sounds like an interesting idea to pursue.

**Comment by mixterj** [comment]
@aisaac maybe?? I think there are a few ways to implement this type of hierarchy but I am not very opinionated on where it goes.

1.  Add hierarchy to the AS - seems a bit clunky and prone to issues

2. Add hierarchy to the Manifests via a partOf property that links to a Collection level Manifest description.

I would tend to lean towards the latter because we already have a Collection level item in the Presentation data model.

**Comment by mixterj** [comment]
Here is what I was thinking about - though I understand this pushes the heavy lifting up to the Manifest/Presentation level.

1. Organization level AS stream with no Collection information

![image](https://user-images.githubusercontent.com/6155034/41422395-d35e8910-6fc6-11e8-9a63-754901187c80.png)

2. Organization level AS stream with Collection information linked to via the individual Manifests

![image](https://user-images.githubusercontent.com/6155034/41422492-02c66c18-6fc7-11e8-9dab-553fb6585869.png)

**Comment by azaroth42** [comment]
Closely related to #36.

**Comment by azaroth42** [comment]
Propose that api#1639 would close this issue, along with the `context` notion in #38.

**Comment by azaroth42** [comment]
Call of 2019-03-20: agree solved by partOf, close
