### ISSUE TITLE
Indexing Manifest seeAlso metadata

### ISSUE THREAD

**Issue by mixterj** [IIIF/discovery#35]
Using AS data to harvest and index Manifests works well due to the reliable structure of the Manifest but the seeAlso metadata is very problematic due to the almost unlimited types/profiles/models that the metadata can take. This makes it very difficult to create a meaningful index record for Manifests. 

One solution to this would be to just care about the seeAlso metadata formats you care about but this can still be problematic due to the data model used by the seeAlso metadata.

Situation A) Yes! I love JSON-ld - but I have no idea how to parse and index BIBFRAME JSON-ld...

Another option is to build/spec profiles for all potential seeAlso metadata types. This seems like a pipe dream to me

Situation B) Here is a laundry lists of profiles to parse seeAlso metadata - but you don't have the one I need...

A rather draconian option would be for the Discovery group to make a recommendation on what type/format/shape the seeAlso metadata should take. 

Situation C) You say I SHOULD use this type of seeAlso metadata - but that does not work for my data...

I know this goes against the Charter but as we continue to pursue the AS harvesting this will continue to be a headache - especially as we start to investigate the more complex harvesting usecases outlined in the [June 13 Discovery Working Group notes](https://docs.google.com/document/d/1fzhFGlVmteqi0iYNS78i7uyqFctuRAcCJZcPjIUBSQY/edit).

**Comment by aisaac** [comment]
Another interesting issue :-)
I'd like to make two comments that may have an influence on @mixterj's options:

- there is ongoing work at W3C on raising the profile of profiles, so to say, and I'm involved. It's at https://www.w3.org/2017/dxwg/, work in progress...

- some aggregators like Europeana may very well participate the promotion of a handful of profiles to ensure that harvesters/indexers would have more opportunities to encounter the same profile(s) more often.

**Comment by azaroth42** [comment]
I agree with the challenge that the issue represents -- the community is by and large fragmented when it comes to metadata, and IIIF has participants from many such communities with the aspiration of bringing in even more distinct domains such as medicine. 

To me, all we can do at this stage is catalog which metadata formats are in use in the community and encourage the different domains to publish what they have and to come to their own consensus around best practices.

**Comment by aisaac** [comment]
@azaroth42 +1 for a start, but I'm wondering whether we may have to go a bit farther...

1. I still think we may have to express some discovery-specific recommendations for the usage of seeAlso next to this. Something like "this is dependent on having a URI for the profile of the metadata, so please get one". I'm still unsure whether establishing URIs to refer to vocabularies/profiles is generalized: there might be a lot of non-RDF cases around. Btw I'm also unsure whether we should happily accept URIs like the one of an XML schema in there.
Also, depending on what the W3C group ends up producing, we may be able to add some recommendations from there. But I'm not expecting it would be much
(@azaroth, for the amateur, I'm also now wondering whether the seeAlso pattern is actually a variation of the much-dreaded DXWG use case for indicating availability of profiles without using a conneg pattern https://github.com/w3c/dxwg/issues/239)


2. When I read http://iiif.io/api/presentation/3.0/#seealso it still seems that it may include descriptions that are not metadata for the resource. The expression "description that is related to the resource" is really vague and could be understood as allowing something else. If yes then we could have to add some qualifier (a motivation?) to make it sure that data consumers can be certain of what they're getting.

**Comment by azaroth42** [comment]
I agree that it indicates that a particular resource conforms to a particular profile. I don't think it's a protocol issue though, so unrelated (thankfully) to w3c/dxwg#239. If the profiles are registered (per https://iiif.io/api/annex/registry/ ) then at least that list is reasonably discoverable. 

Agree that `seeAlso` is less specific than we would like. New proposal is for `context` (which has an even more vague definition, but at least would be less ambiguous in this usage). See #38.

I propose that we can close this issue.

**Comment by aisaac** [comment]
As discussed in the call on 19-09-2018 the group does not see an objection on following the currently proposed approach, far from it :-). But considering that solutions are not so clearly laid out in individual tickets (at least via the fact that they have an impact on several tickets, here for example #34 and #38 ) it's preferable to wait and see what the solution looks like in the spec, and assess then how happy we are with the proposed pattern addressing the original case in this ticket.

**Comment by aisaac** [comment]
Call 17-04-19: This strongly relates to the work of the coming CG on 'discovery for humans'. We defer until the group is active and we can pass the issue to them.

**Comment by azaroth42** [comment]
See #24

**Comment by aisaac** [comment]
Considering the re-scoping of the D4H CG, which doesn't include the building of search indexes for IIIF resources, I suppose we should remove the tag -->d4h .

**Comment by azaroth42** [comment]
Closing, unsolvable. But we do have a registry now for the profiles :)
