### ISSUE TITLE
Do we need a Dataset resource?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#38]
From #36, #37, @aisaac, Stanford discussions, etc ...

Do we need separate resources for the datasets that underlie the IIIF resources, and/or for the IIIF resources themselves?

The entities that we have currently:

* The AS Collection is an ordered list of the Activities that have been carried out. This is a dataset, but of activities, not the resources themselves, IIIF or otherwise.
* The Activities, as entries in the AS "dataset"
* IIIF Manifests, as the objects of the activities (typically), and can be part of Collections.
* IIIF Collections, that Manifests can be part of, for presentation/navigation purposes. These could be considered a "dataset" ... but the intentional vagueness and the presentation motivation for their existence makes them a bad candidate to associate metadata with... the same way that the Manifest is a bad candidate for associating item level metadata with.

Similarly to the manifest having a `seeAlso` to a metadata record, either the AS Collection or the IIIF Collection could have a `seeAlso` to a dataset description.

Having a definition of what the Dataset would represent seems important.  Is it only those resources available by IIIF, or is the scope defined by the institution? For example, if the organization publishes manifests for 30,000 of its 250,000 objects, is the size of the dataset 30k or 250k?

**Comment by beaudet** [comment]
Along the lines of what @aisaac was describing about "not closing the door" in the Discovery spec in #37 , would it be worth considering each IIIF resource type (that the Discovery API drills into further) as one of many potential entity types wrapped in a generic "data set"?   I'm hoping the Discovery API can provide a very basic, yet standard, mechanism for publishing structured data sets in general.  I think it's possible to do that without getting sucked down the metadata rabbit hole and to make allowances for domains, e.g. art museums, to adopt their own standards that can be hooked into this framework as a general structured data publication / change notification mechanism.

**Comment by beaudet** [comment]
I also think it's worth considering use cases that do assume some domain-specific standards, for the thought experiment of making Discovery work for such cases.  For example, using the Discovery API to publish links to LIDO records for a special collection subset, e.g. "The Stieglitz Key Set" as well as IIIF manifests for the objects in that collection that have images and other types of assets that can be presented using the IIIF presentation API.  We don't have to drill down into the specifics of LIDO if we just make the assumption that it's one such standard that our sub-domains might want to use.  We'd focus on the generalities of how to describe a general structured data set's common shared attributes, i.e. answering the question: what are the properties of a base class called "structured data set"?

**Comment by zimeon** [comment]
Per [Presentation 3.0 `seeAlso`](http://iiif.io/api/presentation/3.0/#seealso):

> An external, machine-readable resource such as an XML or RDF description that is related to the resource that has the seeAlso property. ...

we should be clear that “the resource” in above means the AS Collection if that is where the `seeAlso` lives. I don't have trouble with the understanding that perhaps we might have a `seeAlso { type="Dataset" ...}` link to data about the resources for which the AS Collection is activities on because that likely describes those activities as well (e.g. "This set (perhaps an IIIF Collection) of microscope images of leaf sections"). We probably shouldn't think of it extending beyond that, there should perhaps be a link out from the `seeAlso` target to something the set of resources described by the AS Collection (which may or may not correspond with an IIIF Collection) is `partOf` or such.

_Edited to address https://github.com/IIIF/discovery/issues/38#issuecomment-411544137 below_

**Comment by aisaac** [comment]
@zimeon could you qualify the specific meaning of the last two occurrences of 'collection' ? I think it means the IIIF collection/dataset, but I'm not sure...

**Comment by nfreire** [comment]
Hi everyone,

Here are the references to the research done for Europeana I mentioned in the call yesterday.

These are about the use of Dataset description vocabularies, where DCAT, Schema.org and VoID were found suitable to describe datasets fo linked data and the Distributions of those datasets (so that Europeana could harvest them by automatic means).

- A research paper on the case study with the National Library of the Netherlands and the Dutch aggregator (NDE) was published at SEMANTiCS 2018:
(the paper will be open access but is not available yet. Let me know if you'd like me to send you the preprint)
https://2018.semantics.cc/aggregation-cultural-heritage-collections-through-web-data

- During the case study, we prepared these guidelines for describing linked data datasets:
https://github.com/nfreire/Open-Data-Acquisition-Framework/blob/master/opaf-documentation/SpecifyingLodDatasetForEuropeana.md

Cheers

**Comment by azaroth42** [comment]
Here is a two part proposal, that would close #38 #37 #36 #35 and #34:

Recommend `seeAlso` on the objects in the activities, to a further description of the individual object. This mirrors the usage of `seeAlso` in the Presentation API.

Recommend `context` (https://www.w3.org/TR/activitystreams-vocabulary/#dfn-context) on the ActivityStreams Collection, pointing to a description of the Dataset that the Activities act upon. (Alternatively, just use `seeAlso` here as well, but I think this issue acknowledges the extra layer of complexity between dataset of activities and dataset of things represented by IIIF manifests on which the activities are carried out).

**Comment by aisaac** [comment]
I think I can live with this proposal, with the observation that:
- I am not sure that we need a two-part proposal, why not having two proposals to close two sets of issues. #35 seems quite orthogonal to the others, especially.
- when you use 'description of the individual object' or 'description of the Dataset', is it acceptable to use a linked data 'resource' URI or should it be really an information object (i.e. a URI for a document)?

I may have other comments but I'd prefer to see the proposal forked before - and I don't think none of the comments would be a fundamental objection to the proposed patterns. I.e. I may nitpick on the choice of properties, but I don't think I would object to the general shape of the solutions.

**Comment by azaroth42** [comment]
From the [call on 2018-09-04](https://docs.google.com/document/d/1yJvcBvzOIaKkUbx9dremiG2Lvq7_eiM05RmIhTti8qY/edit#), the decision was:

* use `context` on the stream to refer to a description of the set of things that the activity stream covers, which could be in any schema. 

* use `context` in the activity's `object` to refer to the document that describes the thing, which would be identical to the `seeAlso` property in the presentation API.  Rationale for including in the stream is to allow for binary and non IIIF resources to have `context` descriptions. Also for aggregators to add value by providing a link that is not in the Presentation API document.

* Rationale for `context` over `seeAlso` is that we can stick entirely within ActivityStreams, making it easier to implement with off the shelf products.

* Each can have multiple values, in the same way as `seeAlso`.

**Comment by aisaac** [comment]
I like the pattern, but I think we should keep our option open wrt to having context (and not seeAlso) at the level of the AS activity.

As much as I understand the motivation for having the discovery spec nicely bounded in AS, I see a big disadvantage of using a different property than the "main" IIIF specs, while the purpose is largely equivalent. Going against IIIF consistency can be as bad as being consistent with AS.

Using seeAlso would also ensure that any future update/improvement on the spec of seeAlso in the "main" spec to directly benefit the discovery spec.
It would also make sure such future updates/improvements in the main specs would not be hampered by potential conflicts with the use of context in discovery spec (as we're trying to have the same properties on seeAlso and context). With what we've seen about the design of AS, I would not be surprised if there's a strong semantic commitment somewhere that makes no sense and would prevent us to do some smart things.

Besides, I've yet to see an off-the-shelf AS tool that we can re-use and that would thus prove the supposed benefit of keeping our data bound in AS. What are the chances of this happening, against the chance of the IIIF community making their own fit-for-purpose tools?

To be clear: I'm not objecting 100% to using context, but I think the decision should be made in a wider circle as the implications may spill over other IIIF areas.

**Comment by aisaac** [comment]
NB: to facilitate this, we could write down the draft spec with `context` and put an explicit "issue note" reference, explaining the choice and calling for feedback.

**Comment by aisaac** [comment]
As discussed in the call on 19-09-2018 the group does not see an objection on following the currently proposed approach, far from it :-). But considering that solutions are not so clearly laid out in individual tickets (at least via the fact that they have an impact on several tickets, here for example #34 and #35) it's preferable to wait and see what the solution looks like in the spec, and assess then how happy we are with the proposed pattern addressing the original case in this ticket.

**Comment by azaroth42** [comment]
I hate to do this ... but ... in writing up the decision I ran into an alternative that I think is better and has not been discussed.

AS has the notion of [Profiles](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-profile):

> A Profile is a content object that describes another Object [...]

Which have the `describes` property to reference the described Object.  Note that this is an AS `Object`, which is anything other than a Link.

AS does *not* define an inverse relationship for `describes` and hence we can't go from (e.g) an OrderedCollection to a Profile that describes it.  Howeer, we can use JSON-LD's [`@reverse`](https://www.w3.org/TR/json-ld11/#reverse-properties) functionality to create a context entry that uses `as:describes`, but ... in reverse.  We could call it, say, `describedBy`.

Thus:

```
{
  "id": "https://example.org/iiif/all-changes",
  "type": "OrderedCollection",
  "describedBy": {
    "id": "https://example.org/data/dcat.jsonld",
    "type": "Profile",
    "mediaType": "application/ld+json"
  },
  "first": "https://example.org/iiif/page-0",
  "last": "https://example.org/iiif/page-n"
}
```

This would be semantically clean, and more accurate than the current `context` use.  It doesn't introduce new vocabulary (as it uses `@reverse`) but does introduce a new context definition.  It also would mean not having to explain the difference between `@context` and `context`, that will definitely cause confusion.

The entry in the context document would be:

```
  "describedBy": {"@reverse": "as:describes", "@type": "@id", "@container": "@set"}
```

And the above would look like this in Turtle:

```
<https://example.org/data/dcat.jsonld> a as:Profile ;
  as:mediaType "application/ld+json" ;
  as:describes <https://example.org/iiif/all-changes> .

<https://example.org/iiif/all-changes> a as:OrderedCollection ;
  as:first <https://example.org/iiif/page-0> ;
  as:last <https://example.org/iiif/page-n> .
```

**Comment by aisaac** [comment]
As discussed on call 3-10-2018 (https://docs.google.com/document/d/1HRMvc1VM4Jk8-IKVxmNSbv5Td8lAL26lShlmknDF6x0) the `Profile` construct is intended as a description of the one thing refered in the `describes` statement. In our context we have different resources. E.g. one activity stream collection about a dataset's resources on one hand, a dataset on the other hand. So for the time being it is safer to use `context`, in spite of its own issues.

**Comment by azaroth42** [comment]
Now that we have our own discovery context again, rather than trying to make it possible to use off the shelf ActivityStream implementations, we can use `seeAlso` across the board for consistency.  The argument was the this API is targeted at the IIIF community, rather than at the web at large.  There are broader patterns that are likely better suited for general SEO.

Thus, replacing the confusing `context` with the familiar `seeAlso`.

**Comment by azaroth42** [comment]
Call on 2019-03-20: Agree fixed.
