### ISSUE TITLE
 Recommendation on how to reference/describe an IIIF activity stream from a DCAT Distribution?

### ISSUE THREAD

**Issue by nfreire** [IIIF/discovery#40]
In #38 , it is under discussion the possibility to refer to DCAT descriptions of the dataset covered by an Activity Stream (AS).

If a IIIF provider creates a DCAT description of a IIIF dataset/AS, how should the IIIF Change Discovery API endpoint be referenced and described? 
My first thought is that an AS is a dcat:Distribution of a dcat:Dataset. 
Should the Discovery Group prepare a recommendation?

But, in fact, I'm currently convinced that whether or not DCAT descriptions are referenced from IIIF Activity Streams, it would always be relevant for general discovery to have a  IIIF recommendation for DCAT descriptions of IIIF datasets.

**Comment by azaroth42** [comment]
Specifying an application profile for external specifications is not in scope for IIIF work, as established by:

* https://github.com/IIIF/api/issues/1089
* https://github.com/IIIF/api/issues/600 
* https://github.com/IIIF/api/issues/558

Propose to close wontfix.

**Comment by nfreire** [comment]
Ok, I was indeed unsure whether this would be out-of-scope of the group.

Maybe it is something to be addressed somewhere else.

**Comment by aisaac** [comment]
I agree that we shouldn't specify an application profile, so it's certainly a 'wontfix' for our specs. But it seems the discussion could be relevant to understanding what our AS are in relation to another approach. So I would suggest to not close it while at the same time flagging it only for discussion only, and in case there are people in the group who'd be interested in it.

I reckon I'm on a thin line. It's more for a community group than a TSG group. But there won't be a CG on our topic as long as we exist. I guess it's a bit like the discussions on registries of IIIF datasets: it's not on our charter, but if there's community interest we can't really refuse that the discussion happens.

**Comment by azaroth42** [comment]
TSG Call consensus:  Out of scope for the TSG, closing wontfix. We couldn't enforce anything we came up with, regardless, as DCAT isn't our spec.

**Comment by zimeon** [comment]
For reference: [DCAT Distribution](https://www.w3.org/TR/vocab-dcat/#class-distribution) in W3C spec
