### ISSUE TITLE
Named subsets & non-Presentation objects

### ISSUE THREAD

**Issue by atiro** [IIIF/discovery#41]
The most pressing case we have for change discovery is to inform aggregators of changes within a particular subset of our total collection, usually because of some agreement that we share a particular  collection (collection in this sense meaning objects of any one type, or objects belonging to a particular collector, or objects on a particular theme, or any other grouping of objects imaginable).

In this case we would want to use IIIF Discovery for notification solely about this subset, either in images or object metadata. However it is likely that not all of these objects would have public IIIF manifests with canvases, it may be only some would be made available in this way (although perhaps I could create stub manifests that have no canvases but contain a seeAlso to the object record?)

Broadly, this API would be extremely useful to keep aggregators in sync (which is a very convincing case to make internally), but I am trying to think how to do this step-by-step, without needing both sides to implement all the APIs.

Would the use of Discovery API for this purpose make sense and be appropriate, or would this weaken the connection to Presentation too much?. There is mention of "Activities describing changes to other resources", would I be better looking at that? Or is this really more something for ResourceSync ?

**Comment by mattmcgrattan** [comment]
Proposal to  close with reference to https://github.com/IIIF/discovery/issues/12 and https://github.com/IIIF/discovery/issues/42 as a duplicate (#42 covers subsets and #12 covers non-IIIF resources)

IIIF Discovery Call: Feb 6th 2019.

@atiro is this ok with you?

**Comment by atiro** [comment]
Yes!
