### ISSUE TITLE
connecting different activity streams

### ISSUE THREAD

**Issue by mixterj** [IIIF/discovery#42]
If you plan to implement the Discovery API at both the organization level (i.e. here is a list of all the IIIF stuff my organization knows about) and at the collection level (i.e. here are the specific IIIF activities related to a specific collection), is there a way to connect the collection AS back to the organization AS?

as:partOf could be used to connect from the collection AS to the organization AS but there is no inverse in the AS ontology.

**Comment by aisaac** [comment]
Approved in call 31-10-2018 https://docs.google.com/document/d/1vQXEBoT4nwXkiMYbwMtoIz1fJfl2qBxoW8UKyffbVA8/

**Comment by aisaac** [comment]
For the record: #41  provides another use case for this requirement

**Comment by aisaac** [comment]
Call 2019-02-06: Relationship between streams is a partitioning relationship, will be handled in the new @context discussed for #36, #38, #28 .

**Comment by azaroth42** [comment]
Call on 2019-03-20: Agree fixed, closing
