### ISSUE TITLE
Activity Stream Update for item that has become restricted

### ISSUE THREAD

**Issue by mixterj** [IIIF/discovery#47]
What type of AS Activity type should be created when a IIIF Manifest goes from open access to some sort of restricted access?

use case - CONTENTdm has has a variety of different access restriction mechanisms. Items can be open access, restricted by IP range, restricted by login, or restricted by both IP address and login. Collection managers can modify these setting on a per collection basis through a configuration UI.

So what should the AS update be if an collection manager changes a collection from 'open' to 'IP range restricted' (for campus use only for example)?

Solutions:

- Update: but this is a bit misleading because a  crawler might see the Update and try to resolve the Manifest URI only to get a 403 response. But if a crawler is within the range (like a researcher or department on campus) it would be fine

- Delete: Also misleading because if you still have access to the data (researcher/teacher or department on campus) then you would inadvertently throw out this item.

I think the real solution is not prescribing a pattern for AS but rather setting an expectation for what a harvester should expect.

**Comment by aisaac** [comment]
Issue has been discussed on 06-02-2019 at https://docs.google.com/document/d/1WK1QKin7XW_gI4LVGFt2_ltyDd73VaUU-cvMtrxqr6c/
discussion needs to continue

**Comment by azaroth42** [comment]
Consensus on 2/20 call is to add warning about content becoming unavailable, but not to add explicit new activity types.

**Comment by azaroth42** [comment]
Call on 2019-03-20: Agree fixed by 0.3, closing.
