### ISSUE TITLE
Canonical URI for negotiable resources

### ISSUE THREAD

**Issue by mattmcgrattan** [IIIF/discovery#48]
Add a property (as per the usage in the W3C Web Annotation model) to expose the canonical uri for an object that might have a different URL (viz the Content Location as per the explicit recommendation in https://github.com/IIIF/discovery/issues/46).

https://www.w3.org/TR/annotation-model/#other-identities

**Comment by mattmcgrattan** [comment]
Canonical in the anno jsonld @context is:

https://www.w3.org/TR/annotation-vocab/#canonical

http://www.w3.org/ns/oa#canonical

**Comment by azaroth42** [comment]
Has this been discussed on a call? (No references in above comments)
Tagging discuss
