### ISSUE TITLE
what to do when a IIIF Collection is deleted from an Activity Stream perspective?

### ISSUE THREAD

**Issue by mixterj** [IIIF/discovery#54]
this is a use-case most likely applicable to only vendors or aggregators.

When a Collection is permanently deleted or removed from a system or a customer leaves a vender that supports IIIF Change Discovery what should happen to the Activity Stream data?

It is counter-intuitive to delete the Activity Stream stream. Logically a bunch of 'Deletes' would be created BUT what should happen to the related 'dataset' descriptions linked to by the 'seeAlso' property? It seems odd that you would keep them since the Dataset technically would not exist any longer. So should the seeAlso property just be deleted from the Stream data?

I could not find a way to indicate that a DCAT or VoID Dataset not longer exists.

**Comment by aisaac** [comment]
Trying to grasp the scope of the issue: would a similar problem appear in the context of deleted manifests, for the `seeAlso`s that they have?
Do we want to create a specific set of best practices for how to handle deletion in general?

**Comment by aisaac** [comment]
Call 12-06-2019: there could be an activity that records the deletion of the dataset itself.

**Comment by azaroth42** [comment]
Given that non IIIF resources aren't in scope (at the moment), I would simply remove the `seeAlso` reference from the activity's description.

**Comment by azaroth42** [comment]
Discussion on 2019-07-10 call: 

* Registry event for deletion of the stream?
* Dataset / metadata records out of scope for the change stream, but is there an implementation issue here?

Rediscuss when @mixterj is available

**Comment by azaroth42** [comment]
Discussed on 2019-10-30 - It's expected that resources referred to from previous events may no longer be available, such as when a manifest and its related dataset are deleted, then previous updates will refer to documents that today result in a 404.

If stream is deleted completely, should the stream be 404? Would be a burden to keep the references around for a long time.

Can put a Delete event into a stream registry.
Can send a notification out that the stream was Deleted (to subscribers).
Clients need to deal with 404s anyway.

**Comment by azaroth42** [comment]
SHOULD give a 410 GONE response instead of 404 to make the permanence clear.

**Comment by azaroth42** [comment]
Propose close?

**Comment by aisaac** [comment]
ok

**Comment by azaroth42** [comment]
Close, 2020-06-10
