### ISSUE TITLE
add terms/use rights to an Change Discovery feed

### ISSUE THREAD

**Issue by mixterj** [IIIF/discovery#55]
Is there a way to add terms, conditions, or rights to the Change Discovery API feed, outside of the rights associated with the items referenced in the feed?

For example adding a 'non-commercial use' license to Change Discovery API feed even if the items in it are CC0 or something similar.

**Comment by mixterj** [comment]
seems like a dc:rights property at the AS Collection level would do the trick

**Comment by aisaac** [comment]
just a note that we should probably seek to handle this in the exact same way as Presentation API handles rights. And we may have to add a couple of recommendations on the fact that rights at different levels should not contradict. We probably don't need a full model for hierarchical rights, but we shouldn't avoid a bit of discussion.

**Comment by azaroth42** [comment]
:+1: There's nothing in AS that directly supports /conflicts with this, so seems like an easy add.
