### ISSUE TITLE
Name of annotation motivation in Content State API

### ISSUE THREAD

**Issue by aisaac** [IIIF/discovery#57]
In the [current Content State draft's annotation](https://preview.iiif.io/api/content-state-0.3/api/content-state/0.2/index.html#22-form-of-annotation) the motivation is `selecting` .
there has been discussion in the [call 18-09-2019](https://docs.google.com/document/d/1QXycTf-CIMGPCryUl_vFP8lVILYzGl2L7Kkn7dNz2sY/)

> Richard: when will the decision be made wrt the motivation? This would be breaking
> 
> Antoine doesn’t like “selecting” as a motivation, but accepts we need something that is not a Web Annotation motivation. Thinks it may be too generic, and might be misused by others.
> 
> Tom: would be namespaced to the Discovery @context. Agrees it is quite a generic slippery term.
> 
> Antoine: namespacing can still lead to confusion and issues in practice.
> 
> Tom: accepts that that term might come up in other scenarios that might touch on IIIF.
> 
> Antoine: “IIIF Content Selection”
> 
> Glen: "IIIF Selection"?
> 
> Glen: we need to decide on the motivation before we merge

**Comment by aisaac** [comment]
@tomcrane after I've started checking last call's agenda I've realized that the action to create this issue was on you. But as I had started, I've just finished it. I hope you won't mind

**Comment by aisaac** [comment]
@tomcrane @azaroth42 what would you say of using "bookmarking" in the name (and thus make the motivation of sub-concept of the existing `bookmarking` motivation in Web Annotation? It sounds a decent fit with the notion of 'selecting' a part of a resource for later access.
(from https://www.w3.org/TR/annotation-model/#motivation-and-purpose: "The motivation for when the user intends to create a bookmark to the Target or part thereof. For example an Annotation that bookmarks the point in a text where the reader finished reading.")

**Comment by aisaac** [comment]
For the record, there was discussion on this issue at on 2019-10-16, https://docs.google.com/document/d/1ZqFMxpRoL2w7JHVNIjQMXF886fTwi6Ofxns1fEogdLY/

**Comment by aisaac** [comment]
Decision at the above call: we test `contentState` in Ann Arbor and other options and observe reactions.

**Comment by tomcrane** [comment]
The `contentState` motivation is used in the current published 0.2 version:

https://iiif.io/api/content-state/0.2/

...so people can see how they feel about it.

**Comment by aisaac** [comment]
Closed in call 14 May 2020
