### ISSUE TITLE
Remove Move if no implementations

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#58]
Added in 0.4, discussed on 2019-10-30.
Story is: https://github.com/IIIF/iiif-stories/issues/110

No current implementations, but thought to be valuable. Remove before 1.0 if still no implementation.

**Comment by azaroth42** [comment]
We are approaching 1.0 ... are there any implementations of Move or do we need to remove it?

**Comment by aisaac** [comment]
Now that we have described it, would it be possible to keep this pattern in the spec as a non-normative activity type, or even something more informal? This way we could still keep the floor open for feedback (and maybe prototype implementations) without having to be non-backward-compatible if we remove it for good in a later version?
I would rather want to encourage implementations - this pattern can be quite useful, isn't it?

**Comment by azaroth42** [comment]
Yale would have had to have implemented this for YCBA manifests. General agreement to leave it in, even without any explicit implementation.

**Comment by azaroth42** [comment]
Another use case is Wellcome Library moving their URIs to a different domain (iiif.wellcomecollection.org)
