### ISSUE TITLE
URL safe base64 encoding of content state JSON-LD content

### ISSUE THREAD

**Issue by higginsr** [IIIF/discovery#59]
Content state api 0.2 section 2.3 [https://iiif.io/api/content-state/0.2/#23-protocol](https://iiif.io/api/content-state/0.2/#23-protocol) states that JSON-LD content must be base64 encoded. It was suggested during a discovery call that this should be url safe.
There are several implementations of url safe base64 encoding, most of which rely upon encoding and decoding being performed by the same system. As content can be encoded by a completely separate system to that decoding it, an agreed standard should be adopted.
How about [RFC 4648 section 5](https://tools.ietf.org/html/rfc4648#section-5)?

**Comment by azaroth42** [comment]
:+1: to explicitly using 4648 section 5.

**Comment by tomcrane** [comment]
https://github.com/IIIF/api/pull/1935/files#diff-0253cf5682332b3578f13b3e8748b76bR158

The link is to this section, but the text doesn't explicitly mention the RFC number.

**Comment by tomcrane** [comment]
https://preview.iiif.io/api/content-state-comments/api/content-state/0.2/#231-base-64-encoding-with-url-and-filename-safe-alphabet

**Comment by aisaac** [comment]
The minutes of the call on June 10 hints that this one should be closed: https://docs.google.com/document/d/1AM1AefGtF3CS2j2KjMkX3LhdQLxX1w6ZhZAyiUOgf4c/

**Comment by tomcrane** [comment]
Yeah, I'm in the process of adding some more text about base64url encoding which we can look at on the call tomorrow.
