### ISSUE TITLE
Are notifications in-scope for Change Discovery 1.0?

### ISSUE THREAD

**Issue by zimeon** [IIIF/discovery#60]
In discussions of [Roadmap and Discovery at Ann Arbor](https://docs.google.com/document/d/1jxnaE4jNXMmmKSj4raWmFThPZLGvqrP14ERnRjclrr8/edit) (combined notes doc) there was a majority of those expressing an opinion that Change Discovery 1.0 should not include notifications, and notifications should be investigated and added later. This group was not representative of the whole community but prompts me to ask whether a decision on this issue would help spur the process?

The [note in the 0.4 draft](https://iiif.io/api/discovery/0.4/#objectives-and-scope) says:

> Notification of Changes -- This draft version of the specification does not include the subscription mechanism for enabling change notifications to be pushed to remote systems. The current specification only enables the polling pattern where the set of changes must be periodically reprocessed. Notifications are likely to be added in a future version before 1.0.

so that could usefully be updated if notifications end up not be planned for 1.0. release.

**Comment by azaroth42** [comment]
Call on 2019-11-13 was that we should proceed with change discovery and not delay it arbitrarily for notifications.

**Comment by aisaac** [comment]
Minutes of the call: https://docs.google.com/document/d/1DuDsSN2D2cTbf8U2-CAtfby0J0wMCrSA8g-N56KIAHY/

**Comment by azaroth42** [comment]
I think we can close this issue. 1.0 won't have notifications, and consensus seems to be that it shouldn't, until we know more about how best to interact with a pull based system before adding push.

**Comment by azaroth42** [comment]
Close, call on 2020-06-10
