### ISSUE TITLE
Problematic use of HTTPS URI for Creative Commons licenses

### ISSUE THREAD

**Issue by aisaac** [IIIF/discovery#61]
As per @tomcrane 's [comment](https://github.com/IIIF/api/pull/1879#pullrequestreview-313269000), the current version of the Discovery API uses HTTPS URIs for Creative Commons license, while the canonical URIs for machine readable consumption are HTTP ones.

See discussion at https://github.com/IIIF/api/issues/1874 and https://github.com/IIIF/trc/issues/32

**Comment by azaroth42** [comment]
We're now locked in with `http`, as Prezi 3.0 is final.

https://iiif.io/api/presentation/3.0/#rights

Propose close as our hands are tied.

**Comment by aisaac** [comment]
Well, I do want to follow the choice made for Prezi 3.0 (I was vocal about using `http` there!). The problem is that the Change Discovery API is not aligned with that, as it uses `https`: https://iiif.io/api/discovery/0.9/#rights
