### ISSUE TITLE
Use of the word "parent" in definition of OrderedCollection => partOf

### ISSUE THREAD

**Issue by tomcrane** [IIIF/discovery#65]
The full spec and processing algorithm is clear on this, but a reader familiar with `Collection` in the Presentation API might be briefly misguided into thinking that you can have an `OrderedCollection` of OrderedCollections - "refer to a **parent** Ordered Collection ... to have different collections of activities for their paintings from their sculptures".

Perhaps something like

> **partOf**
> This property is used to refer to a larger Ordered Collection, of which this Ordered Collection is part.

(This is very minor, just avoid _parent_ suggesting hierarchy).

**Comment by aisaac** [comment]
proposal from @azaroth42 : replace 'parent' by 'larger'

**Comment by azaroth42** [comment]
Done in 0.5; propose-close

**Comment by azaroth42** [comment]
Close, call on 2020-06-10
