### ISSUE TITLE
Overlapping streams - shared events

### ISSUE THREAD

**Issue by aisaac** [IIIF/discovery#67]
Following an [issue](https://github.com/IIIF/registry/issues/1) raised by @higginsr  about the registry,  there were discussions on [call 2020-01-22](https://docs.google.com/document/d/1VYh6yRIzofsCjf7v3EhP3q1I4DJIqZVr-5C9M6UVZY4/) and [call 2020-02-19](https://docs.google.com/document/d/1gnC4dOwr6WFdVy1ghPHbgp-5Sfvg16Oykih7MoFz4mY/), which clarified that:
- Multiple streams may contain the same events
- Processing multiple streams, you may want to merge them into a single stream, rather than doing streams consecutively.

The first of these call concluded that this could be handled via a recipe, which would tell harvesters what they can expect and suggesting the options. In the second, we questioned a potential recipe as potentially quite shallow (since we basically tell harvesters can proceed as they want). We may as well add a line in the spec that says that events can be contained in different streams (this could be seen as a clarification of the semantics for containment of events in streams)

This issue is raised for discussion and as a reminder for implementation.

**Comment by aisaac** [comment]
Cf discussions on calls [2020-03-04](https://docs.google.com/document/d/1Svu_GhyDFogubSPwPQS7AziKzop8qlxRnx_kqQy6gEk/) and [2020-03-17](https://docs.google.com/document/d/1AEbyHJfdJi_PEom0zsoikr1s2NOSwg9bMTsHgM4gvYM/)

**Comment by azaroth42** [comment]
Close?

**Comment by aisaac** [comment]
I think that the [intro of 3.5](https://iiif.io/api/discovery/0.9/#activity-streams-processing-algorithm) and [section 3.5.4](https://iiif.io/api/discovery/0.9/#processing-multiple) solve the issue. But it would be nice to have the raiser of the issue @higginsr formally confirm!

**Comment by higginsr** [comment]
Yes, I am in a content state

**Comment by aisaac** [comment]
@higginsr this is a powerful argument for keeping the current API name in #70 ;-)

**Comment by azaroth42** [comment]
Closing, call of 2020-06-10
