### ISSUE TITLE
"Content State" API naming

### ISSUE THREAD

**Issue by scossu** [IIIF/discovery#70]
The ["Content State"](https://iiif.io/api/content-state/0.2/) name within the Discovery API seems unclear to me and possibly misleading about its scope. 

Coming from a repository background I cannot help thinking about "content state" in term of change events and versioning. This conception is even strengthened by reading the spec alongside its companion, [Change Discovery](https://iiif.io/api/discovery/0.3/) which deals precisely with state change activities. However, the Content State API spec, as I understand, is focused on identifying specific portions of a IIIF Presentation structure. The "state" being described is probably referred to the viewer, however from discussion at the recent Ann Arbor meeting, it seems like referring to the viewer here is not desirable. 

I propose to change the name from "Content State" to "Content Addressing" or similar terminology, or to tie the "state" term to something else than "content".

**Comment by zimeon** [comment]
Discussion on [2020-05-13 Discovery Call](https://docs.google.com/document/d/1_04YrOXfSTUhaLIDPZBOBI4aZu_amF3f_f62KAg-K4w/edit) did not have significant support for any other names. Suggestion that we should review again on the next Discovery Call and then close without changes (keeping "Content State") unless there is consensus on something else

**Comment by aisaac** [comment]
For the record...
A while ago I had proposed "Presentation State" as it seems more about a 'snapshot' of (or focus on) where the user is in a presentation structure/path. "Content State" hints that the content can change and we snapshot a specific state in such changing content. But that was really about taste: I wouldn't have called "Content State" wrong! Especially now that "Content State" have grown more visible, I can quite easily live with it!

**Comment by azaroth42** [comment]
Could the API be used for non IIIF Presentation API state addressing, or is it specific only to that specific function? One of our principles is to keep APIs loosely coupled but useful in combination, and I think we've done that well with the Change Discovery API -- it is clear how to use it for IIIF resources, but organizations have implemented it for non IIIF resources as well.

IMO, the scope of the API is to describe the (current / desired) state of the content that the viewer is rendering to the user. However it's not only about rendering -- the state of the content could be for used for other, non-rendering purposes. And it's only about the content, not about other states of the consuming application. 

If on Wednesday we can't come to consensus on a different name, we should lock in "Content State" and close the issue.

**Comment by azaroth42** [comment]
Call did not come up with any better name than Content State. 
Agree that there could be more explanation in the introduction about the naming.
