### ISSUE TITLE
Are names of content state attributes SHOULD or MUST?

### ISSUE THREAD

**Issue by tomcrane** [IIIF/discovery#72]
In the current content state draft, `iiif-content` as a GET or POST parameter is a _MUST_, but `data-iiif-content` as an HTML attribute is a _SHOULD_.

* https://preview.iiif.io/api/content-state-comments/api/content-state/0.2/#234-protocol
* https://preview.iiif.io/api/content-state-comments/api/content-state/0.2/#317-common-initialization-parameter

Typically, the owner of the process that is generating the HTML knows what viewer they are embedding and how it is configured. In some scenarios, the content state will have arrived at the page as a GET parameter (must), e.g., ?iiif-content=blah, then supplied to a viewer’s data-iiif-content attribute in dynamically created HTML. 

Is this even in the spec at all? Is it a cookbook recipe only? 
It would aid providers and implementers of viewers if they didn't have to think of a name for this attribute, but it won't break much if they don't use it.

**Comment by tomcrane** [comment]
Removed the warning and pushed updated text.
https://github.com/IIIF/api/pull/1935/commits/f6f01cb9c9ca90e62b9aec7331c6e96220565f49

**Comment by tomcrane** [comment]
Close?

**Comment by azaroth42** [comment]
Done
