### ISSUE TITLE
Notes from reading 0.9 Change Discovery spec

### ISSUE THREAD

**Issue by higginsr** [IIIF/discovery#74]
The default for this spec is still 0.3, which means that internal link in 2.1.4 take you to that version, as does the link https://iiif.io/api/discovery (the links in 3.5 are hardcoded to version 0.9)

At what point does http://iiif.io/api/discovery/1/context.json get created - should there be a place holder?

In section 2 the links Collections and Manifests point to presentation 2.1 rather than 3.0

Section 2.1.2 should be stated more explicitly. It either must be in chronological order or must have a time stamp, otherwise how does it work?

Section 3.2, defining "next" "unless they are the last Page in the Collection" needs lower case p in Page (just to show I was still paying some attention)

I think it needs a section on the Change Discovery Registry even if it is only a link to Github. Otherwise there is nothing about  publishing the whereabouts of your data or finding data published by other repositories.

**Comment by azaroth42** [comment]
Redirects - Needed to remove the links from the previous versions. Done

Context - Should be in place by the time we get to 1.0 ... so in the next few months.

Section 2 links - good catch. These were actually wrong /globally/ in the site, not just this document. Fixed.

2.1.2 - Agreed, fixed.

3.2 - :) Good catch!

Registry - Let's discuss on a call. In Prezi/Image we have a section about registries that we could start from, but they're slightly different sorts of registries in that context.

**Comment by azaroth42** [comment]
Discussion on call 2020-10-14:   Registry link - to be discussed with the community on the next discovery TSG call - 10/28.  need to send agenda out sooner rather than later to maximize attendance.

**Comment by azaroth42** [comment]
Consensus on call of 2020-10-28: Refer to the IIIF registry (registry.iiif.io) in Intro / new subsection of Section 3 of the Change Discovery specification, with a note that there are likely to be multiple registries and that any further registries known will be referenced from the IIIF registry landing page. IIIF-C are okay with maintaining the registry.

**Comment by aisaac** [comment]
Reference to the registry is at https://preview.iiif.io/api/discovery-0-9-1/api/discovery/0.9/#24-registries-of-collections

**Comment by aisaac** [comment]
Call 25-11-2020: can be closed when the PR is merged
