### ISSUE TITLE
Crawler doesn't know when to stop reading activities

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#81]
From WG session call on 2020-12-02:

@workergnome (paraphrased, as I understand it): As the set of pages can be continually appended, it can easily grow very long when there are many objects being tracked. However if there is a refresh of every object, then there's no point a crawler continuing to work backwards through the pages as they won't find anything new.

A solution could be to put a marker in the list when the refresh starts, and crawlers would then know to stop processing when they see a "refresh" activity.

**Comment by workergnome** [comment]
This can also be addressed by publishing (somewhere?) a "do not crawl past" timestamp somewhere, or could be combined with a "bootstrapping" dump.

**Comment by azaroth42** [comment]
Discussion on call 2021-01-06:

Agree is important to cover in the spec.

Option 3: Blow away the stream when you do a refresh. Down side -- if there are deleted resources, then it would be hard to determine which resources should be removed. Particularly problematic when the resource exists in multiple streams, or identifiers change. Spec should describe issues with just starting the stream again.

For aggregators that have already seen the stream, they still need to go back beyond the do not crawl past to look for deletes, until they reach the last point in time. If doing this, then have to publish delete events for any resources that aren't present post-refresh.

**Comment by aisaac** [comment]
A note about this should be added in the spec, which asks for community feedback for the next version..
See discussion at https://docs.google.com/document/d/1DfNCq-Axhe8SgS1AqmZ6PvLN34Pdw8cSsIX20DLqZDg/

**Comment by azaroth42** [comment]
2021-02-03: Considered done, close on merge.
