### ISSUE TITLE
Both APIs need explicit content-type definitions

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#86]
(cf  https://iiif.io/api/presentation/3.0/#63-responses and  https://iiif.io/api/image/3.0/#51-image-information-request )

**Comment by azaroth42** [comment]
Decision on call of 2021-03-03:  Content-State should have the same media type as the Presentation API, as it is just a part of that suite of JSON structures.

**Comment by azaroth42** [comment]
Discussion on call of 2021-03-03: Too many options for Change Discovery API media type and not enough understanding of the pros and cons of each.  @azaroth42 to reach out to the Activity Streams registrant (@jasnell) to explain the situation and ask about precedents, patterns and adoption.

**Comment by jasnell** [comment]
It's been a while since I've had my head in activity streams work but I'm happy to jump on a call to discuss. Hit me up in email and we can get something set up.

**Comment by azaroth42** [comment]
Thanks so much James! Will be in touch momentarily :)

**Comment by azaroth42** [comment]
Considerations from editorial discussion for the Change Discovery API question:

* No compelling evidence or considerations to make a decision, but agreement that there should be some recommendation
  * Should ask for practical use cases for /what/ to do with the information if provided

* Is it a IIIF specific API, even though we've allowed non-IIIF content? Argument for two profile URIs in the param?
-- Add the IIIF profile if and only if there is IIIF resources referenced in the stream, and if not then don't - this would let registry and consumers make an early determination about whether to process the stream or not.

* Consistency with other APIs would suggest `application/ld+json;profile="(something goes here?)"`

Rob to find convenient time to talk with James, and maybe invite to TSG if there is more to discuss

**Comment by jasnell** [comment]
When is the TSG call?

**Comment by jpstroop** [comment]
New use case: Princeton would like to start putting Manifest and Collection URIs in MARC records. We can put the link in the `856 $u`, no problem, but need to designate that this is IIIF-flavored JSON, and not an HTML page. We could put the content-type in `856 $q` if we had one.
