### ISSUE TITLE
IIIF Discovery Context link 404

### ISSUE THREAD

**Issue by mixterj** [IIIF/discovery#92]
The current 0.9 Discovery Spec (https://iiif.io/api/discovery/0.9/) JSON-ld Context link returns a 404 - https://iiif.io/api/discovery/1/context.json

**Comment by azaroth42** [comment]
Running edits with issues to fix with the context in 0/

- [ ] label
- [ ] seeAlso
- [ ] ... + format
- [ ] ... + profile
- [ ] canonical
- [ ] target with scoped context

**Comment by azaroth42** [comment]
Fixed in 1.0
