### ISSUE TITLE
Retrieval needed to determine target of content-state

### ISSUE THREAD

**Issue by azaroth42** [IIIF/discovery#94]
As discussed in slack with @workergnome after his lightning talk in the conference, if the content-state is passed only as a URI, then it is necessary to retrieve the representation and introspect to determine what sort of thing it is -- an annotation or a manifest, for example. While the client will likely have to dereference it at some point, a library that produces some internal representation to drive the client might result in both that library and the main client doing the dereference. Equally, if the client receives a set of content-state URIs, it would need to dereference them all before presenting a UI. 

Once retrieved, the distinction between v2 and v3 type determination comes into play: `type` vs `@type` that could be noted, perhaps in a recipe?

Discuss whether mitigation is needed, and if so, what?

If we think mitigation is warranted, some possibilities:
* Require the URI to ONLY be a manifest (as the most common pattern)
* Recommend against using only the URI pattern to limit the number of such derefs, such as via a warning block in the spec
* Require another param to give the type of the URI, if it's not manifest
* Other?

**Comment by glenrobson** [comment]
Just to note there are examples of non manifests as a URI. I believe Mirador can take collections at:

https://projectmirador.org/embed/?iiif-content=

I've also wrapped Annotate to take annotation lists for the training:

https://iiif.gdmrdigital.com/annona/index.html?iiif-content=https://dnoneill.github.io/annotate/annotations/fullbayeux-list.json

**Comment by azaroth42** [comment]
TSG Call 2021-09-15: Tried to come up with any alternative that would allow for URI to be passed with some additional information as to the type of the resource, but...
* Requires separation of the two parameters, which then would require encoding
* Only matters for independent, cooperating implementations rather than a single implementation in a client
* In the browser context, even if the resource is requested twice, it will be served from cache, limiting any latency

So ... TSG opinion is that while there is some limitation added by this, the value of having a simple single URI as a valid content state outweighs the concerns in this particular issue.
